site_name: ""

theme:
  name: material
  font: false  # Disable Material font handling
  logo: assets/images/tenx-logo.png
extra:
   font:
    text: Inter
    code: Fira Code
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&display=swap
extra_css:
  - stylesheets/custom.css

